name: 26_4-tag-presubmit
concurrency: presubmit
on:
  pull_request_target:
    paths:
      - .github/actions/presubmit/action.yml
      - .github/workflows/26.4-tag-presubmit.yml
      - pipelines/bitnami/compat.yaml
      - 26.4/*
jobs:
  build:
    name: Verify image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/presubmit
        with:
          archs: amd64 #,arm64
          tag: 26.4
