name: 26_4-tag-release
on:
  # schedule:
  #   # Weekly
  #   - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - .github/actions/tag-release/action.yml
      - .github/workflows/26.4-tag-release.yml
      - pipelines/bitnami/compat.yaml
      - 26.4/**
  workflow_dispatch:
jobs:
  build:
    name: Release image with tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tag-release
        with:
          archs: amd64 #,arm64
          tag: "26.4"
