name: "26.4-presubmit"
on:
  pull_request:
    paths:
      - .github/actions/presubmit/action.yml
      - .github/workflows/26.4-presubmit.yml
      - pipelines/bitnami/compat.yaml
      - 26.4/**
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    name: Verify image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/presubmit
        env:
          MELANGE_PRIVATE_KEY: ${{ secrets.MELANGE_PRIVATE_KEY }}
        with:
          tag: "26.4"
