name: "26.5-presubmit"
on:
  pull_request:
    paths:
      - .github/actions/presubmit/action.yml
      - .github/workflows/26.5-presubmit.yml
      - pipelines/bitnami/compat.yaml
      - 26.5/**
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    name: Verify image
    runs-on: ubuntu-latest
    # environment: presubmit-approval
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/presubmit
        with:
          archs: amd64 #,arm64
          tag: "26.5"
